# Generated by Django 3.2.3 on 2021-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211114_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/2021/11/14/defaultavatar_TVDmA4n.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
