# Generated by Django 3.2.3 on 2021-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/main/defaultavatar.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
